# Generated by Django 4.0 on 2021-12-29 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('voting_date', models.DateField(auto_now_add=True)),
                ('vote', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_%(class)s_related', to='auth.user')),
                ('deleted_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by_%(class)s_related', to='auth.user')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='voting_employee', to='auth.user')),
            ],
            options={
                'db_table': 'votes',
                'ordering': ['id'],
            },
        ),
    ]
