# Generated by Django 4.0 on 2021-12-26 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0001_initial'),
        ('employee', '0003_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('vote', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_%(class)s_related', to='employee.user')),
                ('deleted_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by_%(class)s_related', to='employee.user')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='voting_employee', to='employee.user')),
                ('resturant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='voted_resturant', to='resturant.resturant')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_%(class)s_related', to='employee.user')),
            ],
            options={
                'db_table': 'votes',
                'ordering': ['id'],
                'unique_together': {('date', 'resturant', 'employee')},
            },
        ),
    ]
