# Generated by Django 4.0 on 2021-12-26 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0001_initial'),
        ('employee', '0004_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='date',
            new_name='voting_date',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voting_date', 'resturant', 'employee')},
        ),
    ]
