# Generated by Django 4.0 on 2021-12-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_rename_date_vote_voting_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voting_date', 'employee', 'vote')},
        ),
    ]
