# Generated by Django 4.0 on 2021-12-28 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_user_is_active_alter_user_is_staff_and_more'),
        ('resturant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionResturant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_%(class)s_related', to='employee.user')),
                ('deleted_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by_%(class)s_related', to='employee.user')),
                ('resturant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='champio_resturant', to='resturant.resturant')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_%(class)s_related', to='employee.user')),
            ],
            options={
                'db_table': 'champion_resturants',
                'ordering': ['id'],
            },
        ),
    ]
