# Generated by Django 4.0 on 2021-12-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0002_championresturant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='championresturant',
            unique_together={('date', 'resturant')},
        ),
    ]
