version: "3.8"

services:
  lunchmanagement-db:
    image: postgres:12.3-alpine
    restart: always
    volumes:
      - lunchmanagement-volume:/var/lib/postgresql/data/
    # environment:
    #   POSTGRES_DB: "lunchmanagement"
    #   POSTGRES_PASSWORD: "12345"
    ports:
      - 5434:5432
    networks:
      - lunchmanagement_network
  web:
   build:
     context: .
   command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
   container_name: web
   ports:
     - 8000:8000
   environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "lunchmanagement"
      POSTGRES_PASSWORD: "12345"  
   networks:
     - lunchmanagement_network
   depends_on:
     - lunchmanagement-db
   restart: on-failure:3

volumes:
  lunchmanagement-volume:

networks:
 lunchmanagement_network:
   driver: bridge